### PR TITLE
Amended parallel appender to immediately proceed with shutdown once all messages have flushed

### PR DESCRIPTION
**Pull request by stas-a**
Amended ParallelForwardingAppender to immediately proceed with shutdown once all messages have flushed. It will sleep and check every 100ms until flush timeout is expired or all events have flushed. Otherwise it will behave same as before and wait for th specified time. Moved timeout assignemnt out of ActivateOptions so that it can be set from unit tests. Added appropriate unit tests.

### CODE REVIEW

**Comment by rcollette** [comment]
I'm assuming this is to obtain quicker shutdown.  Seems to make sense but I am curious about the use case that motivated looking into this.

**Comment by stas-a** [comment]
The use case is simple: I was testing the parallel appender using a console
app and noticed that messages could be lost if an appender was relatively
slow and the app exited quickly. Added LogManager.Shutdown() to ensure
messages are flushed. Then the test app was getting stuck for extra 5
seconds during every run, regardless of number of messages to flush.

So, to recap, console app or any other app that runs and terminates quickly
may incur message loss unless it calls LogManager.Shutdown(). And if it
does, it will be getting stuck for extra X seconds waiting for timeout.

I guess in most cases one can do without calling LogManager.Shutdown() and
never encounter message loss. But if there is a slow appender, all bets are
off.

02 авг. 2016 г. 3:01 пользователь "Richard Collette" <
notifications@github.com> написал:

**Comment by rcollette** [comment]
@cjbhaines  -  This looks good.   Historically it looks like you merge and then bump the nuspec version number.   Same process here or should the nuspec version be bumped as part of the merge?

**Comment by stas-a** [comment]
Awesome! Thanks!

**Comment by cjbhaines** [comment]
Thanks guys! packages pushed to NuGet.

**Pull request merged**
